### ISSUE TITLE
compatiblity issue

### ISSUE THREAD

**Issue by FlorianHeigl** [lampwins/np_autodiscovery#2]
It seems that this plugin can't work anymore - getting the below traceback.

```
netbox_1         | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox_1         | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox_1         | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox_1         | Traceback (most recent call last):
netbox_1         |   File "/opt/netbox/netbox/netbox/settings.py", line 602, in <module>
netbox_1         |     plugin_config = plugin.config
netbox_1         | AttributeError: module 'np_autodiscovery' has no attribute 'config'
netbox_1         |
netbox_1         | During handling of the above exception, another exception occurred:
netbox_1         |
netbox_1         | Traceback (most recent call last):
netbox_1         |   File "./manage.py", line 10, in <module>
netbox_1         |     execute_from_command_line(sys.argv)
netbox_1         |   File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
netbox_1         |     utility.execute()
netbox_1         |   File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
netbox_1         |     self.fetch_command(subcommand).run_from_argv(self.argv)
netbox_1         |   File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
netbox_1         |     self.execute(*args, **cmd_options)
netbox_1         |   File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
netbox_1         |     output = self.handle(*args, **options)
netbox_1         |   File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 82, in wrapped
netbox_1         |     saved_locale = translation.get_language()
netbox_1         |   File "/opt/netbox/venv/lib/python3.8/site-packages/django/utils/translation/__init__.py", line 254, in get_language
netbox_1         |     return _trans.get_language()
netbox_1         |   File "/opt/netbox/venv/lib/python3.8/site-packages/django/utils/translation/__init__.py", line 57, in __getattr__
netbox_1         |     if settings.USE_I18N:
netbox_1         |   File "/opt/netbox/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 83, in __getattr__
netbox_1         |     self._setup(name)
netbox_1         |   File "/opt/netbox/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 70, in _setup
netbox_1         |     self._wrapped = Settings(settings_module)
netbox_1         |   File "/opt/netbox/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 177, in __init__
netbox_1         |     mod = importlib.import_module(self.SETTINGS_MODULE)
netbox_1         |   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
netbox_1         |     return _bootstrap._gcd_import(name[level:], package, level)
netbox_1         |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
netbox_1         |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
netbox_1         |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
netbox_1         |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
netbox_1         |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
netbox_1         |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
netbox_1         |   File "/opt/netbox/netbox/netbox/settings.py", line 605, in <module>
netbox_1         |     raise ImproperlyConfigured(
netbox_1         | django.core.exceptions.ImproperlyConfigured: Plugin np_autodiscovery does not provide a 'config' variable. This should be defined in the plugin's __init__.py file and point to the PluginConfig subclass.
```

in `init.py` I find a config variable, but it doesn't look very similar to the standard (...point to the PluginConfig subclass.)

```
default_app_config = 'np_autodiscovery.apps.NPAutoDiscoveryConfig'
```

**Comment by FlorianHeigl** [comment]
If I look at netbox_qrcode, it could be that one needs to fill the following into `__init.py__`

```
from extras.plugins import PluginConfig
from .version import __version__

class NpAutodiscoveryConfig(PluginConfig):
    name = 'np_autodiscovery'
    verbose_name = 'Autodiscovery'
    description = 'auto discovery of existing devices in a network'
    version = '1.0.0'
    author='John Anderson',
    author_email='lampwins@gmail.com',
    required_settings = []
    default_settings = {}
config = NpAutodiscoveryConfig
```

**Comment by rlachman** [comment]
How do you run this??
